

# backend:
#   name: git-gateway
#   branch: master # Branch to update (optional; defaults to master)
#   accept_roles: #optional - accepts all users if left out
#     - admin
#     - editor
#     - translator


backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  repo: chadananda/st-dev # Path to your GitHub repository


# This line should *not* be indented
publish_mode: editorial_workflow


# These lines should *not* be indented
media_folder: "static/assets" # Media files will be stored in the repo under static/assets
public_folder: "/assets" # The src attribute for uploaded media will begin with /assets


collections:
  - name: "articles" # Used in routes, e.g., /admin/collections/articles
    label: "Article" # Used in the UI
    folder: "content/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}_{{language}}" # Filename template, e.g., YYYY-MM-DD-title.md
    filter:
      field: language
      value: en
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "pubdate", widget: "datetime"}
      - {label: "Featured Image", name: "img", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Language", name: "language"}
      - {label: "id", name: "id"}
      - {label: "baseid", name: "baseid"}
      - {label: "Body", name: "body", widget: "markdown"}

      # fields: tags, category, snip, id, baseid




